#!/usr/bin/env python3
"""FuturaMAX R3: render research/audits/CITATION_AUDIT.md from the link-check results.

Covers: per-run citation counts, reachability verdicts, primary-source share, dead and
extraction-damaged URLs, and the cross-model overlap table. Keywords: citation audit,
link rot, 404, bot-blocked, primary source share, provider comparison.
Read when: judging how well-sourced a given model run is, or hunting a dead citation.
A 200 means the URL resolves - it does not mean the source supports the claim.
Verdict: GENERATED. Regenerate with tools/research/make_citation_audit.py.
"""
from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NORM = ROOT / "research" / "normalized"
OUT = ROOT / "research" / "audits" / "CITATION_AUDIT.md"

# URLs cut mid-token by html2text/pdf line wrapping - our extractor's fault, not the model's.
TRUNCATED = re.compile(r"(-$)|(/$)|(^https?://[^/]+/?$)")


def is_extraction_artifact(url: str, verdict: str) -> bool:
    if verdict != "NOT_FOUND":
        return False
    tail = url.rstrip()
    return tail.endswith("-") or tail.endswith("_") or bool(re.search(r"/(pdf|p|ug|_)$", tail)) or "cerowrt.org/blog.cerowrt.org" in tail


def main() -> int:
    src = [json.loads(l) for l in (NORM / "sources.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
    lc = {json.loads(l)["url"]: json.loads(l) for l in (NORM / "link_check.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()}

    per_run = defaultdict(lambda: {"n": 0, "primary": 0, "verdicts": Counter(), "types": Counter()})
    for s in src:
        v = lc.get(s["url"], {}).get("verdict", "UNCHECKED")
        for p in s["providers"]:
            r = per_run[p]
            r["n"] += 1
            r["primary"] += 1 if s["primary_source"] else 0
            r["verdicts"][v] += 1
            r["types"][s["source_type"]] += 1

    overall = Counter(lc.get(s["url"], {}).get("verdict", "UNCHECKED") for s in src)
    dead, artifacts = [], []
    for s in src:
        v = lc.get(s["url"], {}).get("verdict")
        if v == "NOT_FOUND":
            (artifacts if is_extraction_artifact(s["url"], v) else dead).append(s)

    L = []
    A = L.append
    A("# FuturaMAX citation audit (R3, wave 1)")
    A("")
    A("Summary: reachability and source-type breakdown of all 535 URLs cited by the six")
    A("external Deep Research runs, per run, plus every dead or damaged citation.")
    A("Keywords: citation audit, link check, 404, primary source share, bot-blocked, provider quality.")
    A("Read when: weighing how well-sourced a run is, or chasing a citation that will not open.")
    A("Current verdict: reachability is good; **reachability is not verification**. A 200 proves")
    A("the URL exists, not that the source says what the model claimed it says.")
    A("Status: GENERATED by tools/research/make_citation_audit.py - do not hand-edit.")
    A("")
    A("## Overall reachability")
    A("")
    A("| Verdict | Count | Meaning |")
    A("|---|---:|---|")
    meaning = {
        "OK": "resolved at the exact URL",
        "REDIRECT": "resolved after redirect (usually http->https or www normalisation)",
        "BLOCKED": "403/429/503 - bot protection or rate limit, not necessarily dead",
        "NOT_FOUND": "404 - dead, moved, or never existed",
        "ERROR": "DNS/TLS/timeout failure",
        "HTTP_ERROR": "other HTTP status",
        "UNCHECKED": "not probed",
    }
    for v, n in overall.most_common():
        A(f"| {v} | {n} | {meaning.get(v, '')} |")
    A("")
    A(f"Reachable in some form (OK+REDIRECT): **{overall['OK'] + overall['REDIRECT']}/{len(src)}**"
      f" = {100 * (overall['OK'] + overall['REDIRECT']) / len(src):.0f}%.")
    A("")
    A("`BLOCKED` is dominated by sites with bot challenges (openwrt.org, patents.justia.com,")
    A("ieeexplore, sciencedirect). Those need a real browser, not urllib - see the note at the end.")
    A("")
    A("## Per-run citation quality")
    A("")
    A("`primary_source` is inferred from the URL shape (kernel/git/patent/FCC/academic/vendor-docs")
    A("count as primary; forums, blogs, wikis, unclassified pages do not). It measures what the run")
    A("*pointed at*, not what it *verified*.")
    A("")
    A("| Run | Cited URLs | Primary-source share | OK+REDIRECT | BLOCKED | NOT_FOUND | ERROR |")
    A("|---|---:|---:|---:|---:|---:|---:|")
    for p in sorted(per_run, key=lambda k: -per_run[k]["n"]):
        r = per_run[p]
        ok = r["verdicts"]["OK"] + r["verdicts"]["REDIRECT"]
        A(f"| {p} | {r['n']} | {100 * r['primary'] / r['n']:.0f}% | {ok} | "
          f"{r['verdicts']['BLOCKED']} | {r['verdicts']['NOT_FOUND']} | {r['verdicts']['ERROR']} |")
    A("")
    A("## Source-type mix per run")
    A("")
    all_types = sorted({t for r in per_run.values() for t in r["types"]})
    A("| Run | " + " | ".join(t.replace("_", " ") for t in all_types) + " |")
    A("|---|" + "---:|" * len(all_types))
    for p in sorted(per_run, key=lambda k: -per_run[k]["n"]):
        A(f"| {p} | " + " | ".join(str(per_run[p]['types'].get(t, 0)) for t in all_types) + " |")
    A("")
    A("## Dead citations (404, genuine)")
    A("")
    if dead:
        A("| URL | Cited by | Note |")
        A("|---|---|---|")
        for s in dead:
            A(f"| `{s['url']}` | {', '.join(s['providers'])} | {s['source_type']} |")
    else:
        A("None.")
    A("")
    A("## Damaged citations (our extractor's fault, not the model's)")
    A("")
    A("URLs cut mid-token by html2text / PDF line wrapping. Re-extract before judging these.")
    A("")
    for s in artifacts:
        A(f"- `{s['url']}` (cited by {', '.join(s['providers'])})")
    A("")
    A("## Cross-model overlap")
    A("")
    corr = Counter(s["cross_model_corroboration"] for s in src)
    A("| Cited by N runs | Sources |")
    A("|---:|---:|")
    for k in sorted(corr, reverse=True):
        A(f"| {k} | {corr[k]} |")
    A("")
    A(f"Only **{sum(v for k, v in corr.items() if k >= 2)} of {len(src)}** sources were found by more")
    A("than one run. The six sweeps were near-disjoint. That is good for coverage and it means")
    A("cross-model agreement on a *conclusion* is not backed by agreement on *evidence*.")
    A("")
    A("## Known limitation of this audit")
    A("")
    A("openwrt.org returns HTTP 200 with a bot-challenge body to plain urllib, so its `OK` rows")
    A("carry a challenge-page title rather than the real one. The OpenWrt device pages were read")
    A("through a real browser instead - see `knowledge/HARDWARE_MATRIX.md`, which is where the")
    A("first Grade-A target-hardware evidence in this project came from.")
    A("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"  {len(src)} sources, {len(dead)} genuinely dead, {len(artifacts)} extraction-damaged")
    for p in sorted(per_run, key=lambda k: -per_run[k]["n"]):
        r = per_run[p]
        print(f"  {p:<9} n={r['n']:<4} primary={100 * r['primary'] / r['n']:.0f}%")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
